project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls', namespace='page')), 
    path('websites/', include('website.urls', namespace='website')),
    path('v2/', include('app_v2.urls', namespace='v2')),
    path('v3/', include('v3.urls', namespace='v3')), 
]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

v3/urls.py
from django.urls import path 
from .views import * 

app_name = 'v3' 

urlpatterns = [
    path('', index, name='index'), 
    path("<int:id>/", website_details, name="website-details"), 
    path("page/<int:id>/", page_details, name='page-details'),
    path("page/<int:id>/export/", export_code, name='export-code'),
    path('page/<int:page_id>/upload_from_excel/', upload_from_execl, name='upload-from-excel'),
    path('del-field/<int:id>/', delete_screen_field, name='del-screen-field'),
    path("download-template/", download_excel_standard_file, name='download-template'),
    path("get-field-info/", get_field_info, name='get-field-info'), 
    path('fields-branch-interface/', fields_branch_interface, name='fields-branch-interface'), 
    path('fields-branch-interface/<int:id>/', single_tool_field_branch, name='single_tool_field_branch'), 
]

v3/models.py
from django.db import models

class ScreenFieldType(models.Model):

    name = models.CharField(max_length=200, unique=True)
    display_name = models.CharField(max_length=200)
    cmd = models.TextField() 

    def __str__(self):
        return self.name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'ScreenFieldType'
        verbose_name_plural = 'ScreenFieldTypes'


class DbType(models.Model):
    name = models.CharField(max_length=150, blank=True, null=True, unique=True)

    def __str__(self):
        return self.name 

    class Meta:
        verbose_name = 'نوع قاعدة بيانات'
        verbose_name_plural = 'أنواع قواعد البيانات'

class Website(models.Model):
    name = models.CharField(max_length=200) 
    url = models.URLField(verbose_name="رابط الموقع")
    db_type = models.ForeignKey(DbType, related_name='websites', on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(null=True, blank=True) 


    def __str__(self):
        return self.name 

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Website'
        verbose_name_plural = 'Websites'


class Page(models.Model):
    website = models.ForeignKey('Website', related_name='pages', on_delete=models.CASCADE)
    name = models.CharField(max_length=200 )

    def __str__(self):
        return self.name 

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'


class ScreenField(models.Model): 
    page = models.ForeignKey('Page', related_name='s_fields', on_delete=models.CASCADE)
    sf_type = models.ForeignKey(ScreenFieldType, on_delete=models.CASCADE) 
    name = models.CharField(max_length=200)

    color = models.CharField(verbose_name="اللون", max_length=30, blank=True, null=True)
    width = models.CharField(verbose_name="العرض (بكسل)", max_length=5, blank=True, null=True)
    height = models.CharField(verbose_name="الارتفاع (بكسل)" , max_length=5, blank=True, null=True)
    bg_color = models.CharField(verbose_name="لون الخلفية", max_length=30, blank=True, null=True) 
    bg_url = models.CharField(verbose_name="مسار (رابط ) الخلفية", max_length=255, blank=True, null=True) 
    font_size = models.CharField(max_length=3, verbose_name="حجم الخط (بكسل)", blank=True, null=True)
    font_family = models.CharField(max_length=100, verbose_name="عائلة الخط (اسم الخط)", blank=True, null=True)
    font_weight = models.IntegerField(default=100, verbose_name="وزن الخط (من ١٠٠ إلى ٩٠٠)", blank=True, null=True)
    padding = models.CharField(max_length=5, verbose_name="الهوامش الداخلية (بكسل)", blank=True, null=True)
    margin = models.CharField(max_length=5, verbose_name="الهوامش الخارجية (بكسل)", blank=True, null=True)
    cmd = models.TextField(verbose_name="الأمر البرمجي", null=True, blank=True) 

    def save(self, *args, **kwargs):
        self.cmd = self.sf_type.cmd 
        tag_index = self.cmd.index('>')
        
        self.cmd = self.cmd[:tag_index] + f" id=id{self.id}" + self.cmd[tag_index:]
         
        super(ScreenField, self).save(*args, **kwargs)


    def __str__(self): 
        return self.name 
    

class ExcelTemplate(models.Model):

    file = models.FileField(upload_to='excel/')

    class Meta: 
        verbose_name = 'قالب اكسل'
        verbose_name_plural = "قوالب الاكسل"



class PreBuiltField(models.Model):

    tool = models.ForeignKey("base.Tool", verbose_name="التقنية / الأداة", on_delete=models.SET_NULL, blank=True, null=True, related_name='fields')
    name = models.CharField(verbose_name="اسم الحقل", max_length=200)
    project= models.CharField(verbose_name="المشروع", max_length=200, null=True, blank=True) 
    details = models.TextField(verbose_name="وصف الحقل")
    cmd = models.TextField(verbose_name="سطر الأمر") 

    

    class Meta:
        verbose_name = "حقل "
        verbose_name_plural = "مستودع الحقول"

    def __str__(self):
        return self.name

v3/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import * 
from urllib.parse import quote
from django.http import HttpResponseRedirect
from django.http import HttpResponse
import os 
from zipfile import ZipFile
from openpyxl import load_workbook

from base.models import Tool 

# Create your views here.

def index(request):

    """
        index page contains all websites 
        add new website 
    """

    if request.POST:
        name = request.POST.get('website-name-input') 
        url= request.POST.get('website-url-input') 
        description = request.POST.get('description-input') 
        dbtype = request.POST.get('dbtype-input')
        dbtype_obj = DbType.objects.get(name=dbtype) 

        if name != "" or name != None: 
            Website.objects.create(
                name = name, 
                url = url,
                description= description,
                db_type=dbtype_obj
            )


    websites = Website.objects.all() 
    dbtypes = DbType.objects.all() 

    context = {
        'websites': websites,
        'dbtypes': dbtypes, 
    } 
    return render(request, 'v3/index.html', context)


def website_details(request, id):
    website = get_object_or_404(Website, id=id)

    if request.POST: 
        page_name = request.POST.get('page-name-input') 
        
        Page.objects.create(
            website=website, 
            name= page_name 
        )

        return redirect('v3:website-details', id=id) 



    context ={
        'website': website, 
    }
    return render(request, 'v3/website-details.html', context)


def page_details(request, id): 

    page = get_object_or_404(Page, id=id) 
    sf_types = ScreenFieldType.objects.all() 

    if request.POST: 
        sf_type_input = request.POST.get('sf_type-input') 
        field_name = request.POST.get('field-name-input') 

        sf_type_obj = ScreenFieldType.objects.get(name=sf_type_input)

        ScreenField.objects.create(
            page=page, 
            sf_type=sf_type_obj, 
            name=field_name 
        )

        return redirect('v3:page-details', id=id) 


    context = {
        'page': page, 
        'sf_types': sf_types, 
    } 
    return render(request, 'v3/page-details.html', context)



def export_code(request, id): 
    page = get_object_or_404(Page, id=id)

    # filename = f"{page.name}.txt"
    names = [
        f"{page.name}.txt", 
        f"{page.name}.html"
    ]
    

    for filename in names: 
    
        with open(filename, 'w+', encoding='utf-8') as code: 
            ## generate css code 
            code.write('<!DOCTYPE html>\n')
            code.write('<html dir="rtl" lang="ar" >\n')
            code.write('<head>\n')
            code.write(f'<title>{page.name}</title>\n')
            code.write('<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">')
            code.write('<style>\n') 

            for field in page.s_fields.all(): 
                code.write(f'#id{field.id} {{\n')
                code.write(f"\theight: {field.height};\n")
                code.write(f'\tcolor: {field.color};\n')
                

                code.write(f"\tfont-size: {field.font_size}px; \n")
                code.write(f'}}\n')
            # height
            # width 
            # color 
            # bgcolor 
            # bgurl 
            # padding
            # margin 
            # fontsize
            # fontweight 
            # fontfamily 

            code.write('</style>\n' )
            code.write('</head>\n')

            code.write('<body>\n')

            code.writelines("""
            <!--
            يوجد بعض النصائح الخاصة بعدة عناصر اكتبها لك هنا لتساعدك أثناء تخصيص صفحتك
            الأزار: الكلاس الافتراضي الموجود في الأزرار هو btn-primary

            يمكنك تغييره لعدة قيم أخرى حسب رغبتك 
            زر خطر: btn-danger 
            زر تحذير: btn-warning
            زر غامق: btn-dark 
            زر معلومات: btn-info 
            زر نجاح العملية: btn-success                 
            -->
            """)

            for field in page.s_fields.all(): 
                cmd = field.cmd 
                cmd = str(cmd)

                code.write("\t" + cmd) 
                code.write('\n')
            
            code.write('</body>\n')
            
            code.write('<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>')
            
            code.write("\n")
            
            code.write('<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>')
            
            code.write('\n')

            code.write('</html>')


    
    output_zipfile_name = f"{page.website.id}output-{page.id}.zip"

    with ZipFile(output_zipfile_name, 'w') as zip_object: 
        for name in names: 
            zip_object.write(name)


    with open(output_zipfile_name, 'rb') as f: 
        file_content = f.read() 

    # response = HttpResponse(file, content_type="text/html")
    # response['Content-Disposition'] = f'attachment; filename="{filename}"'
    
    # return response


    # URL encode the filename to ensure compatibility
    encoded_filename = quote(output_zipfile_name)

    # Create the HTTP response to download the file
    response = HttpResponse(file_content)
    response['Content-Type'] = 'application/x-zip-compressed'
    # response['Content-Disposition'] = f'attachment; filename*=UTF-8\'\'{encoded_filename}'
    response['Content-Disposition'] = f'attachment; filename={encoded_filename}'

    os.remove(output_zipfile_name) 
    
    return response


def upload_from_execl(request, page_id): 
    page = get_object_or_404(Page, id=page_id)

    if request.POST: 
        file = request.FILES['file-input']
        wb = load_workbook(filename=file) 

        sheet1 = wb['Sheet1']

        for i in range(1, 1000): 
            cellA = 'A'+ str(i+1) 
            cellB = 'B'+ str(i+1) 
            cellA_value = sheet1[cellA].value 
            cellB_value = sheet1[cellB].value 

            if cellA_value == None or cellB_value == None: 
                break; 
            

            sf_type = get_object_or_404(ScreenFieldType, name=cellB_value)

            ScreenField.objects.create(
                page=page, 
                sf_type=sf_type, 
                name = cellA_value
                
            )


    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def delete_screen_field(request, id): 
    get_object_or_404(ScreenField, id=id).delete() 

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    

def download_excel_standard_file(request): 
    
    file = ExcelTemplate.objects.last().file 
    file_path = file.path 
    file_name= file.name 

    with open(file_path, 'rb') as f: 
        file_data = f.read() 

        response = HttpResponse(file_data, content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = f'attachment; filename="template.xlsx"'
    
    return response


def get_field_info(request): 
    if request.GET: 
        id = request.GET.get('id') 

        field = get_object_or_404(ScreenField, id=id) 

        sf_types = ScreenFieldType.objects.all() 

        context = {
            'field': field,
            'sf_types': sf_types, 
        }
        return render(request, 'v3/overlay-edit-screenfield.html', context)
    
    elif request.POST: 
        field_id__input = request.POST.get('field__ID') 
        field = get_object_or_404(ScreenField, id=field_id__input)

        field_name__input = request.POST.get('filed__name__input')
        
        field_type__input = request.POST.get('sf_type__input')
        field_type = get_object_or_404(ScreenFieldType, name=field_type__input)

        field_height_input = request.POST.get('field__height__input') 
        field_width_input = request.POST.get('field__width__input') 

        color_input = request.POST.get('color__input') 
        bgcolor_input = request.POST.get('bgcolor__input') 

        field_padding__input = request.POST.get('field_padding_input')

        field_margin__input = request.POST.get('field_margin_input') 

        field_fontsize__input = request.POST.get('font_size__input') 
        field_fontfamily__input = request.POST.get('font_family__input') 
        field_fontweight__input = request.POST.get('font_weight__input') 

        field.name = field_name__input 
        field.sf_type =field_type 
        field.height = field_height_input 
        field.width = field_width_input 
        field.color = color_input 
        field.bg_color = bgcolor_input 
        field.padding = field_padding__input 
        field.margin = field_margin__input 
        field.font_size = field_fontsize__input
        field.font_family = field_fontfamily__input 
        field.font_weight = field_fontweight__input

        field.save() 

        return redirect("v3:page-details", id=field.page.id)


def fields_branch_interface(request): 

    tools = Tool.objects.all() 


    context = {
        'tools': tools, 
    } 
    return render(request, 'v3/fields-branch-interface.html', context)


def single_tool_field_branch(request, id): 
    tool = get_object_or_404(Tool, id=id) 

    context = {
        'tool': tool,
        'fields': tool.fields.all() 
    }

    return render(request, 'v3/single_tool_field_branch.html', context)

v3/templates/v3/fields-branch-interface.html
{% extends 'base.html' %}

{% block title %}
مستودع الحقول | اختر التقنية
{% endblock title %}

{% block content %}

<style>

    .item {
        {% comment %} background: red; {% endcomment %}
        padding: 1rem;
        border-radius: 1rem;
        border: 1px solid #121212;
    }

    .section__content {
        margin-top: 1rem;
    }

</style>

<section>
    <div class="container">
        <div>
            <h1>مستودع الحقول</h1>
            <p>الميثاق الأول للحقول في مختلف تقنيات المبرمج، الهدف منه تسريع الإنتاج البرمجي وتسهيل بناء قواعد البيانات على المبرمج</p>
        </div>
        <div class="section__content">
            <div class="grid">

                {% for tool in tools %}

                <div class="item">
                    <h4>{{tool}}</h4>
                    <p>
                        {% if tool.description %}
                            {{tool.description}}
                        {% endif %}
                    </p>
                    <p>عدد الحقول: <span>{{tool.fields.count}}</span>حقل</p>
                    <a href="{% url 'v3:single_tool_field_branch' tool.id %}" class="btn btn-solid-dark">تفاصيل</a>
                </div>

                {% endfor %}
                
            </div>
        </div>
    </div>
</section>


{% endblock content %}

v3/templates/v3/overlay-edit-screenfield.html
<div class="popup">
    <a id="btn-close-popup">x</a>

    <form action="{% url 'v3:get-field-info' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="field__ID" value="{{field.id}}">
      <div class="form_field">
        <label for="" class="form-label">اسم الحقل</label>
        <input
          type="text"
          class="input"
          placeholder="اكتب اسم الحقل"
          name="filed__name__input"
          value = "{{field.name}}"
        />
      </div>

      <div class="form_field">
        <label for="" class="form-label">نوع الحقل</label>
        <select name="sf_type__input" id="">
          {% comment %} <option value="" disabled>اختر نوع الحقل</option> {% endcomment %}
          <option value="{{field.sf_type.name}}">{{field.sf_type.display_name}}</option>
          {% for sf_type in sf_types %}
          <option value="{{sf_type}}">{{sf_type.display_name}}</option>
          {% endfor %}
        </select>
      </div>

      {% comment %} الطول {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">الطول</label>
        <input
          type="text"
          class="input"
          placeholder="ادخل طول الحقل بالبكسل"
          name="field__height__input"
          value="{{field.height}}"
        />
      </div>

      {% comment %} العرض {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">العرض</label>
        <input
          type="text"
          class="input"
          placeholder="ادخل عرض الحقل بالبكسل"
          name="field__width__input"
          value="{{field.width}}"
        />
      </div>

      {% comment %} لون النص {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">اختر لون النص</label>
        {% comment %}
        <input
          type="text"
          class="input"
          placeholder="ادخل عرض الحقل بالبكسل"
          name="field__width__input"
        />
        {% endcomment %}
        <input type="color" name="color__input" id="" value="{field.color}" />
      </div>

      {% comment %} لون الخلفية {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">اختر لون الخلفية</label>
        <input type="color" name="bgcolor__input" id="" value="{{field.bg_color}}" />
      </div>

      {% comment %} الهوامش الداخلية {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">الهوامش الداخلية</label>
        <input
          type="text"
          class="input"
          placeholder="اكتب قيمة الهوامش الداخلية بالبكسل"
          name="field_padding_input"
          value="{{field.padding}}"
        />
      </div>

      {% comment %} الهوامش الخارجية {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">الهوامش الخارجية</label>
        <input
          type="text"
          class="input"
          placeholder="اكتب قيمة الهوامش الخارجية بالبكسل"
          name="field_margin_input"
          value="{{field.margin}}"
        />
      </div>

      {% comment %} حجم الخط {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">حجم الخط</label>
        <input
          type="text"
          class="input"
          placeholder="أدخل حجم الخط بالبكسل"
          name="font_size__input"
          value="{{field.font_size}}"
        />
      </div>

      {% comment %} عائلة الخط {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">عائلة الخط</label>
        <input
          type="text"
          class="input"
          placeholder="أدخل عائلة الخط (اسم الخط)"
          name="font_family__input"
          value="{{field.font_family}}"
        />
      </div>

      {% comment %} وزن الخط {% endcomment %}
      <div class="form_field">
        <label for="" class="form-label">وزن الخط</label>
        <input
          type="text"
          class="input"
          placeholder="أدخل وزن الخط من ١٠٠ إلى ٩٠٠"
          name="font_weight__input"
          value="{{field.font_weight}}"
        />
      </div>

      <button type="submit" class="btn btn-solid-dark">حفظ التعديلات</button>
    </form>
  </div>

v3/templates/v3/page-details.html
{% extends 'base.html' %} {% load static %} {% block title %} {{page.website}} |
{{page}} {% endblock title %} {% block stylesheets %}

<link rel="stylesheet" href="{% static 'css/old-main.css' %}" />

<style>
  header {
    display: none !important;
  }

  body {
    background-image: url("{% static 'images/old-bg.jpg' %}");
  }
  input,
  select {
    padding: 8px;
    width: 300px;
    max-width: 100%;
    margin: 1rem 0;
    border-radius: 8px;
    border: none;
    outline: none;
  }

  .col * {
    color: white;
  }

  table {
    width: 100%;
    overflow-x: auto;
    max-width: 100%;
    border-collapse: collapse;
  }

  table thead tr {
    background: #f9f9f9;
  }

  table thead th {
    text-align: right;
  }

  table th,
  table td {
    padding: 10px 20px;
  }

  table tbody tr {
    border-bottom: 1px solid #f9f9f950;
  }

  table tbody tr:nth-child(even) {
    background: #f9f9f990;
  }

  .field_types__wrapper {
    display: flex;
    flex-wrap: wrap;
    gap: 2rem;
  }

  .field_type {
    flex: 1;
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 1rem;
  }

  .field_type input {
    width: auto;
  }

  label {
    color: white;
  }
</style>

{% endblock stylesheets %} {% block content %}

<section>
  <div class="container">
    <div class="section__heading">
      <h1>{{page}}</h1>
      <hr />

      <h1>اضافة حقول شاشة</h1>
      <form
        method="post"
        enctype="multipart/form-data"
        action="{% url 'v3:upload-from-excel' page.id %}"
      >
        {% csrf_token %}
        <label for="file-input">ارفع ملف اكسل</label>
        <p>
          يمكنك إضافة حقول الشاشة من خلال ملفات الاكسل حيث يمكنك تحميل القالب
          المعتمد لرفع الحقول بالشكل المناسب لقواعد البيانات في نظامنا
        </p>
        <a href="{% url 'v3:download-template' %}" class="btn btn-solid-dark"
          >تحميل ملف الاكسل المعتمد</a
        >
        <input
          type="file"
          name="file-input"
          id="file-input"
          accept=".xlsx"
          required
        />

        <button type="submit" class="btn btn-solid-dark">رفع ملف اكسل</button>
      </form>

      <form action="" method="post">
        {% csrf_token %}
        <div class="field">
          <input
            type="text"
            placeholder="اكتب اسم الحقل"
            required
            name="field-name-input"
          />
        </div>

        <div class="field">
          <p>نوع الحقل*</p>

          <div class="field_types__wrapper">
            {% for type in sf_types %}
            <div class="field_type">
              <label>{{type.display_name}}</label>
              <input
                type="radio"
                name="sf_type-input"
                value="{{type.name}}"
                id=""
                required
              />
            </div>
            {% endfor %}
          </div>
        </div>

        <button class="btn btn-solid-dark" type="submit">إنشاء حقل</button>
      </form>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="section__heading">
      <h1>جميع الحقول</h1>
    </div>

    <div class="section__content">
      <table>
        <thead>
          <tr>
            <th>اسم الحقل</th>
            <th>نوع الحقل</th>
            <th>إجراء</th>
          </tr>
        </thead>

        <tbody>
          {% for field in page.s_fields.all %}

          <tr>
            <td>{{field.name}}</td>
            <td>{{field.sf_type.display_name}}</td>
            <td style="display: flex; flex-wrap: wrap">
              <a
                class="btn btn-solid-dark btn-sm"
                style="margin-top: 0"
                data-cmd="{{field.sf_type.cmd}}"
                >نسخ الكود</a
              >
              <a
                href="{% url 'v3:del-screen-field' field.id %}"
                class="btn btn-solid-danger btn-sm"
                style="margin-top: 0"
                >حذف</a
              >
              <a data-id="{{field.id}}" class="btn btn-solid-dark btn-edit-field" style="margin-top: 0"
                >تعديل</a
              >
            </td>
          </tr>

          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <a href="{% url 'v3:export-code' page.id %}" class="btn btn-solid-dark"
      >سحب كود الصفحة</a
    >
  </div>
</section>

<br>

{% comment %} popup layer {% endcomment %}
<section class="popup_wrapper">
  <div class="container">
    <div class="popup">
      <a id="btn-close-popup">x</a>

      <form action="" method="POST">
        <div class="form_field">
          <label for="" class="form-label">اسم الحقل</label>
          <input
            type="text"
            class="input"
            placeholder="اكتب اسم الحقل"
            name="filed__name__input"
          />
        </div>

        <div class="form_field">
          <label for="" class="form-label">نوع الحقل</label>
          <select name="sf_type__input" id="">
            <option value="" disabled>اختر نوع الحقل</option>
            {% for sf_type in sf_types %}
            <option value="{{sf_type}}">{{sf_type.display_name}}</option>
            {% endfor %}
          </select>
        </div>

        {% comment %} الطول {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">الطول</label>
          <input
            type="text"
            class="input"
            placeholder="ادخل طول الحقل بالبكسل"
            name="field__height__input"
          />
        </div>

        {% comment %} العرض {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">العرض</label>
          <input
            type="text"
            class="input"
            placeholder="ادخل عرض الحقل بالبكسل"
            name="field__width__input"
          />
        </div>

        {% comment %} لون النص {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">اختر لون النص</label>
          {% comment %}
          <input
            type="text"
            class="input"
            placeholder="ادخل عرض الحقل بالبكسل"
            name="field__width__input"
          />
          {% endcomment %}
          <input type="color" name="color__input" id="" />
        </div>

        {% comment %} لون الخلفية {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">اختر لون الخلفية</label>
          <input type="color" name="bgcolor__input" id="" />
        </div>

        {% comment %} الهوامش الداخلية {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">الهوامش الداخلية</label>
          <input
            type="text"
            class="input"
            placeholder="اكتب قيمة الهوامش الداخلية بالبكسل"
            name="field_padding_input"
          />
        </div>

        {% comment %} الهوامش الخارجية {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">الهوامش الخارجية</label>
          <input
            type="text"
            class="input"
            placeholder="اكتب قيمة الهوامش الخارجية بالبكسل"
            name="field_margin_input"
          />
        </div>

        {% comment %} حجم الخط {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">حجم الخط</label>
          <input
            type="text"
            class="input"
            placeholder="أدخل حجم الخط بالبكسل"
            name="font_size__input"
          />
        </div>

        {% comment %} عائلة الخط {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">عائلة الخط</label>
          <input
            type="text"
            class="input"
            placeholder="أدخل عائلة الخط (اسم الخط)"
            name="font_family__input"
          />
        </div>

        {% comment %} وزن الخط {% endcomment %}
        <div class="form_field">
          <label for="" class="form-label">وزن الخط</label>
          <input
            type="text"
            class="input"
            placeholder="أدخل وزن الخط من ١٠٠ إلى ٩٠٠"
            name="font_weight__input"
          />
        </div>

        <button type="submit" class="btn btn-solid-dark">حفظ التعديلات</button>
      </form>
    </div>
  </div>
</section>

<script>

  let popupWrapper = document.querySelector('.popup_wrapper')

  let btnClosePopup = document.querySelector("#btn-close-popup");
  btnClosePopup.addEventListener("click", () => {
    popupWrapper.style.display = "none";
  });

  // get edit buttons from the table
  let editButtons = document.querySelectorAll(".btn-edit-field");
  editButtons.forEach((btn) => {
    btn.addEventListener("click", () => {
      // ajax request 
      $.ajax({
        url: "/v3/get-field-info/", 
        type: "GET", 
        data: {
          id: btn.dataset.id 
        }, 
        success: (res) => {
          $(".popup_wrapper .container").html(res)
          let btnClosePopup = document.querySelector("#btn-close-popup");
          btnClosePopup.addEventListener("click", () => {
            popupWrapper.style.display = "none";
          });
        }, error: (requestobj, err, err_thrown) => {

        }
      })
      popupWrapper.style.display = 'block'
    });
  });
</script>

{% endblock content %}