project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls', namespace='page')), 
    path('websites/', include('website.urls', namespace='website')),
    path('v2/', include('app_v2.urls', namespace='v2')),
    path('v3/', include('v3.urls', namespace='v3')), 
]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

v3/urls.py
from django.urls import path 
from .views import * 

app_name = 'v3' 

urlpatterns = [
    path('', index, name='index'), 
    path("<int:id>/", website_details, name="website-details"), 
    path("page/<int:id>/", page_details, name='page-details'),
    path("page/<int:id>/export/", export_code, name='export-code'),
    path('page/<int:page_id>/upload_from_excel/', upload_from_execl, name='upload-from-excel'),
    path('del-field/<int:id>/', delete_screen_field, name='del-screen-field'),
    path("download-template/", download_excel_standard_file, name='download-template'),
    path("get-field-info/", get_field_info, name='get-field-info'), 
    path('fields-branch-interface/', fields_branch_interface, name='fields-branch-interface'), 
    path('fields-branch-interface/<int:id>/', single_tool_field_branch, name='single_tool_field_branch'), 
]

website/urls.py
from django.urls import path 
from .views import * 

app_name = 'website' 

urlpatterns = [
    path('all/', all_websites, name='all-websites'),    
    path('<int:id>/', website_details, name='website-details'), 
    path('create/', create_new_website, name='create-new-website'), 
    path('ajax-all-websites/', ajax_all_websites, name='ajax-all-websites'), 
    path('del-websites/<int:id>/', del_website, name='del-website'), 
    path('add-page/', add_page, name='add-page'), 
    path('add-database/', add_database, name='add-database'), 
    path('db-details/<int:db_id>/', db_details, name='db-details'), 
    path('add-table/', add_table, name='add-table'), 
    path('del-table/<int:id>/', del_table, name='del-table'), 
    path('table-details/<int:table_id>/', table_details, name='table-details'), 
    path('table-details/add-field/', add_field, name='add-field'), 


    path('page/<int:id>/', page_details, name='page-details'),
    path('page/preview/<int:id>/', page_preview, name='page-preview'),
]

base/models.py
from django.db import models

# Create your models here.


class Tool(models.Model):
    name = models.CharField(max_length=250, verbose_name="اسم اللغة / إطار العمل")
    description = models.TextField(verbose_name="نبذه وتفاصيل عن التقنية", null=True, blank=True)
    def __str__(self):
        return self.name 

    class Meta:
        verbose_name = 'أداة / إطار عمل '
        verbose_name_plural = 'أدوات / أطر عمل'

class DBType(models.Model):
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE, verbose_name="اللغة / إطار العمل")
    name = models.CharField(max_length=150, verbose_name="الاسم")

    def __str__(self):
        return str(f"{self.tool} | {self.name}")

    class Meta:
        verbose_name = 'نوع قاعدة بيانات'
        verbose_name_plural = 'أنواع قواعد البيانات'

class DbFieldType(models.Model):

    db_type = models.ForeignKey(DBType, on_delete=models.CASCADE, related_name='fields_types')
    name = models.CharField(max_length=250, verbose_name="اسم نوع البيانات")
    display_name = models.CharField(verbose_name="الاسم الظاهر", max_length=200)
    cmd = models.TextField() 
    

    def __str__(self):
        return self.name

base/views.py
from django.shortcuts import render

# Create your views here.

templates/ajax-all-fields.html
{% for field in table.fields.all %}

<tr>
    {% comment %} <td>1</td> {% endcomment %}
    <td class="field_name">{{field.name}}</td>
    <td>{{field.description}}</td>
    <td>{{field.data_type.display_name}}</td>
    <td class="db_field_actions">
        <a href="#" class="btn btn-sm btn-solid-dark">تفاصيل</a>
        <a href="#" class="btn btn-sm btn-solid-danger">حذف</a>
        <a class="btn btn-sm btn-outline btn-copy-cmd" data-cmd="{{field.data_type.cmd}}" onclick="copyCmd(this)">نسخ الكود</a>
        
    </td>
</tr>
{% endfor %}

templates/ajax-all-tables.html
{% for table in db.tables.all %}
                            
                            
<tr>
    <td>1</td>
    <td>
        <a href=""> <!-- click to open table details -->
            {{table.name}}
        </a>
    </td>
    <td>{{table.fields.count}}</td>
    <td class="db__table__actions">
        <a href="{% url 'website:table-details' table.id %}" class="btn btn-outline">تفاصيل</a>
        <a href="" class="btn btn-solid-danger">حذف</a>
    </td>
</tr>
{% endfor %}

templates/ajax_all_pages.html
<div class="grid website-pages-grid">
    {% if website.pages.all %}
        {% for page in website.pages.all %}

        <div class="col page">
            <h3>{{page.name}}</h3>

            <a href="#" class="btn btn-outline btn-open-code">افتح الكود</a>
        </div>

        {% endfor %}
    {% else %}
        <center>
            <h3>لا يوجد صفحات لعرضها</h3>
        </center>
    {% endif %}

</div>

templates/ajax_all_websites.html
<div class="grid all-websites-grid">
    {% for website in websites %}
    <div class="col website">
        <h3>{{website.name}}</h3>
        <p>
            {{website.description}}
        </p>
        <p>
            عدد قواعد البيانات: 
            {{website.databases.count}}
        </p>
        <a href="{% url 'website:website-details' website.id %}" class="btn btn-outline btn-open-website">تفاصيل الموقع</a>
    </div>
    {% endfor %}
</div>

templates/ajax_website_databases.html
{% for db in website.databases.all %}
<div class="col database">
    <h3>
        {{db.name}}
    </h3>

    
    <a href="{% url 'website:db-details' db.id %}" class="btn btn-outline btn-open-code">التفاصيل</a>

</div>
{% endfor %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}    
    </title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- <link rel="stylesheet" href="{% static 'css/all.min.css' %}"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block stylesheets %}{% endblock stylesheets %}
</head>
<body>
    

    <header>
        <!-- <div class="container"> -->
            <div class="logo-container">
                <p class="logo-text">
                    <a href="">
                        بالإشارة إلى
                    </a>
                </p>
            </div>
            <nav >
                <ul>
                    <li><a href="{% url 'page:index' %}" class="list-item">الرئيسية</a></li>
                    <li><a href="#" class="list-item">قواعد البيانات</a></li>
                    <li><a href="{% url 'website:all-websites' %}" class="list-item">المواقع</a></li>
                    <li><a href="#" class="list-item">القوالب الجاهزة</a></li>
                    <li><a href="{% url 'v3:fields-branch-interface' %}" class="list-item">مستودع الحقول</a></li>
                </ul>
            </nav>
            <div class="profile-btns">
                <a href="">
                    <img src="./images/user-solid(1).svg" alt="">
                </a>
                <a href="#" class="user__name">عبدالله محمد</a>
            </div>

            <div class="burger-menu">
                <i class="fa-solid fa-bars"></i>
            </div>
        <!-- </div> -->
    </header>


    <div class="container">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>


    {% block content %}{% endblock content %}



    <!-- <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script> -->
    <script src="{% static 'js/jquery-3.7.1.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/database-details.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    {{db.name}}
{% endblock title %}
    

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/database-details.css' %}">    
{% endblock stylesheets %}
    


{% block content %}
    
    
    <input type="hidden" name="db_id_input" value="{{db.id}}">

    <section class="db__tables">
        <div class="container">
            <div class="section__heading">
                <h1 class="section__heading__title">قاعدة بيانات الفرع الرئيسي</h1>
                <p class="section__heading__text">
                    <br>
                    <form >
                        {% csrf_token %}
                        <input type="text" class="text-input input" id="table-name-input" name="table-name-input" placeholder="اكتب اسم الجدول">
                    </form>
                    <button class="btn btn-solid-dark btn-add-table">إضافة جدول</button>
                </p>
            </div>
            <div class="section__content">
                <!-- اسم الجدول هيكون كذلك عبارة عن رابط لتفاصيل الجدول -->
                <table>
                    <thead>
                        <tr>
                            <td>ID</td>
                            <td>اسم الجدول</td>
                            <td>عدد الحقول</td>
                            <td>الإجراءات</td>
                        </tr>
                    </thead>
                    <tbody class="db-tables">
                        
                        {% for table in db.tables.all %}
                            
                        <tr>
                            <input type="hidden" name="table_id_input" value="{{table.id}}">    
                            <td>1</td>
                            <td>
                                <a href="{% url 'website:table-details' table.id %}">
                                    {{table.name}}
                                </a>
                            </td>
                            <td>{{table.fields.count}}</td>
                            <td class="db__table__actions">
                                <a href="{% url 'website:table-details' table.id %}" class="btn btn-outline">تفاصيل</a>
                                <a class="btn btn-solid-danger btn-del-table">حذف</a>
                            </td>
                        </tr>
                        {% endfor %}



                    </tbody>
                </table>
            </div>
        </div>
    </section>


    <script src="{% static 'js/add-table.js' %}"></script>
    {% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
الرئيسية
{% endblock title %}


{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/add-website-form.css' %}">
{% endblock stylesheets %}



{% block content %}


    <section class="all-websites">
        <div class="container">
            <div class="section__heading">
                <h1 class="section__heading__title">جميع المواقع</h1>
                <p class="section__heading__text">
                    لإضافة موقع املأ النموذج
                </p>
                <form method="POST">
                    {% csrf_token %}
                    <div class="add-website-form">

                            <div class="field">
                                <p>اسم الموقع</p> 
                                <input name="website-name-input" type="text" placeholder="اكتب اسم الموقع" class="input text-input">
                            </div>

                            <div class="field">
                                <p>التقنية / الأداة</p>
                                <select class="" name="website-tool-input" id="website-tool-input">
                                    {% for tool in tools %}
                                        <option value="{{tool.id}}">{{tool.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>


                            <div class="field">
                                <p>وصف الموقع</p>
                                <textarea name="website-description-input" id="" placeholder="اكتب وصف الموقع" class="" ></textarea>
                            </div>

                    </div>
                </form>
                <a id="btn-add-website" class="btn btn-solid-dark">إنشاء موقع جديد</a>
            </div>
            <div class="section__content" id="section__all_websites">
                {% comment %} <div class="grid all-websites-grid">
                    {% for website in websites %}
                    <div class="col website">
                        <h3>{{website.name}}</h3>
                        <p>
                            {{website.description}}
                        </p>
                        <p>
                            عدد قواعد البيانات: 
                            {{website.databases.count}}
                        </p>
                        <a href="{% url 'website:website-details' website.id %}" class="btn btn-outline btn-open-website">تفاصيل الموقع</a>
                    </div>
                    {% endfor %}
                </div> {% endcomment %}
            </div>
        </div>
    </section>

    <br>
    <section id="ai-section">
        <div class="container">
            <div class="section__heading">
                <h1 class="section__heading__title">
                    مساعدك الشخصي
                </h1>
                <p>
                    مساعد شخصي مربوط بالذكاء الاصطناعي جاهز للإجابة على أسئلتك
                </p>
            </div>
            <div class="section__content">
                <div class="question__box">
                    <input type="text" placeholder="اكتب سؤالك... " class="text-input input">
                    {% comment %} <a href="" class="btn btn-solid-dark btn-sm">اسأل</a> {% endcomment %}
                    <button class="btn btn-solid-dark">اسأل</button>
                </div>
            </div>
        </div>
    </section>

    <script src="{% static 'js/index.js' %}"></script>


{% endblock content %}

    

templates/page-details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{page.name}}
{% endblock title %}
    

{% block stylesheets %}
    
    

    <!-- start highlights js  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/androidstudio.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>

    <!-- end highlights js -->



    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="./css/main.css">
    <link rel="stylesheet" href="./css/page-details.css">

    <style>
        .django-ace-widget {
            width: 100% !important; 
        }
    </style>

{% endblock stylesheets %}



{% block content %}
    
    

    <section class="page-code">
        <div class="container">
            <div class="section__header">
                <h1 class="section__heading__title">الرئيسية</h1>
                <a href="{% url 'website:page-preview' page.id %}" class="btn btn-outline">معاينة</a>
            </div>
            <br>
            <form method="POST">

                {% csrf_token %}
                {{form.media}}

                <div class="section__content">
                    <!-- here is code editor -->

                    <div class="code-div">
                        <p>
                            <i class="fa-brands fa-html5"></i>
                            HTML
                        </p>
                        {{form.html}}
                        <!-- <textarea name="html-code" id="html-code" onkeyup="run()"></textarea> -->
                    </div>

                    <div class="code-div">
                        <p>
                            <i class="fa-brands fa-css3-alt"></i>
                            CSS
                        </p>
                        <!-- <textarea onkeyup="run()" name="css-code" id="css-code"></textarea> -->
                         {{form.css}}
                    </div>

                    <div class="code-div">
                        <p>
                            <i class="fa-brands fa-js"></i>
                            JS
                        </p>
                        {{form.js}}
                        <!-- <textarea name="js-code" id="js-code" onkeyup="run()"></textarea> -->
                    </div>

                    <!-- <iframe id="output-iframe" name="output-iframe" ></iframe> -->

                    <div class="page-actions">
                        <!-- <a href="#" class="btn btn-outline">حفظ</a> -->
                        <button type="submit" class="btn btn-outline">حفظ</button>
                        <a href="#" class="btn btn-solid-danger">حذف الصفحة</a>
                    </div>
                </div>

            </form>

        </div>
    </section>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/go.min.js"></script>
    <script>
        /*
        hljs.highlightAll();

        let htmlCode = document.querySelector('#html-code'); 
        let cssCode = document.querySelector('#css-code'); 
        let jsCode = document.querySelector('#js-code'); 
        let outputIframe = document.querySelector('#output-iframe'); 

        function run () { 
            outputIframe.contentDocument.body.innerHTML  = htmlCode.value + "<style>" + cssCode.value + "</style>"
            outputIframe.contentWindow.eval(jsCode.value); 
        }


        let textareas = document.querySelectorAll('textarea').forEach((text) => {
            text.addEventListener('keydown', function(e) {
                if (e.key == 'Tab') {
                  e.preventDefault();
                  var start = this.selectionStart;
                  var end = this.selectionEnd;
              
                  // set textarea value to: text before caret + tab + text after caret
                  this.value = this.value.substring(0, start) +
                    "\t" + this.value.substring(end);
              
                  // put caret at right position again
                  this.selectionStart =
                    this.selectionEnd = start + 1;
                }
              });
        })

        */

    </script>


{% endblock content %}

templates/table-details.html
{% extends 'base.html' %}
{% load static %}



{% block title %}
    {{table}}
{% endblock title %}
    

{% block stylesheets %}
    <link rel="stylesheet" href="{% static '/css/table-details.css' %}">    

    <style>


        .alert { 
            position: fixed;
            top: 0; 
            right: 0;
            width: 100%;
            max-width: 100%;
            min-height: 100vh; 
            display: flex;
            align-items: center;
            justify-content: center;
            background: #10101030; 
            display: none;
        }

        .alert__wrapper { 
            background: white; 
            width: 400px; 
            min-height: 200px;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            row-gap: 1rem;
            border-radius: 1rem;
            box-shadow: 0 4px 10px #f9f9f950;
            animation: alertpop .5s 0s ; 
        }

        .alert__wrapper i {
            font-size: 3rem;
            color: #198754;
        }

        @keyframes alertpop {
            from {
                transform: scale(0);
            } to {
                transform: scale(1);
            }
        }

    </style>

{% endblock stylesheets %}
    


{% block content %}
    
    
    <section>
            <input type="hidden" name="table_id" value="{{table.id}}">
            <div class="container">
                <div class="section__heading">

                    <h1 class="section__heading__title">
                        <a href="{% url 'website:website-details' table.db.website.id %}">{{table.db.website.name}}</a>
                        /
                        <a href="{% url 'website:db-details' table.db.id %}">{{table.db.name}}</a>
                        / 
                        {{table.name}}
                    </h1>
                </div>
                <div class="section__content add-field">
                    <h3>إضافة حقل</h3>
                    <div class="fields__types" style="display: flex; gap:2rem; flex-wrap: wrap;">

                        {% for field_type in fields_types %}
                        
                            <div class="field_type" style="gap: 1rem;">
                                <label class="field_type__label">{{field_type.display_name}}</label>
                                <input type="radio" required name="field__type" data-field_type_id="{{field_type.id}}">
                            </div>

                        {% endfor %}

                    </div>
                    <br>
                    <input type="text" placeholder="اكتب اسم الحقل بالإنجليزية بدون مسافات" class="text-input input" id="field__name">
                    <label for="" class="form-text" style="font-size: .8rem; color: #00000090;">
                        * اكتب اسم الحقل بالإنجليزية بدون مسافات مثال: book_name
                    </label>
                    <br>
                    <br>
                    <input type="text" placeholder="وصف الحقل" class="input text-input" id="field__description">
                    <form method="POST" id="add-field-form">
                        {% csrf_token %}
                        <button class="btn btn-solid-dark btn-add-new-field">إضافة حقل</button>
                    </form>
                </div>
                <br>
                <div class="section__content table_fields_table">
                    <table>
                        <thead>
                            <tr>
                                {% comment %} <td>ID</td> {% endcomment %}
                                <td>اسم الحقل</td>
                                <td>وصف الحقل</td>
                                <td>نوع الحقل</td>
                                <td>الاجراءات</td>
                            </tr>
                        </thead>
                        <tbody id="all-fields">
                            {% for field in table.fields.all %}
                            
                            <tr>
                                {% comment %} <td>1</td> {% endcomment %}
                                <td class="field_name">{{field.name}}</td>
                                <td>{{field.description}}</td>
                                <td>{{field.data_type.display_name}}</td>
                                <td class="db_field_actions">
                                    <a href="#" class="btn btn-sm btn-solid-dark">تفاصيل</a>
                                    <a href="#" class="btn btn-sm btn-solid-danger">حذف</a>
                                    <a class="btn btn-sm btn-outline btn-copy-cmd" data-cmd="{{field.data_type.cmd}}" onclick="copyCmd(this)">نسخ الكود</a>
                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div> 



    </section>

    <div class="alert">
        
        <div class="alert__wrapper">
            <i class="fa-regular fa-circle-check "></i>
            <p>تم نسخ الكود بنجاح</p>
            <a class="btn btn-solid-dark btn-close-alert">إغلاق النافذة</a>
        </div>

    </div>


    <script>

        let showAlert = () => { 
            let alertElement = document.querySelector('.alert'); 
            alertElement.style.display= 'flex';

            let btnClose = alertElement.querySelector('.btn-close-alert');
            btnClose.addEventListener('click', () => {
                alertElement.style.display = 'none';
            })

        }

        function copyText(text) {
            // Create a temporary text area element
            var tempTextArea = document.createElement("textarea");
            tempTextArea.value = text;
            
            // Append the text area to the document body (required for selection to work)
            document.body.appendChild(tempTextArea);
            
            // Select the text in the text area
            tempTextArea.select();
            
            // Copy the selected text to the clipboard
            document.execCommand("copy");
            
            // Remove the temporary text area from the document
            document.body.removeChild(tempTextArea);
        }
        
        let copyCmd = (e) => {
            let cmdText = e.dataset.cmd; 
            copyText(cmdText); 
            showAlert(); 
        }

        /*
        let btnCopyCmd = document.querySelectorAll('.btn-copy-cmd'); 
        btnCopyCmd.forEach((btn) => {
            btn.addEventListener('click', () => {
                let cmd = btn.parentElement.parentElement.querySelector('.field_name').textContent + " = " + btn.dataset.cmd; 
                console.log(cmd); 

                let cmdInputElement = document.createElement('input') 
                cmdInputElement.hidden = true; 
                cmdInputElement.value = cmd; 

                copyText(cmd); 

                // navigator.clipboard.writeText(cmdInputElement.value); 

                // show alert with message 
                showAlert() 
                
            })
        })
        */ 
    </script>

    <script src="{% static 'js/add-field.js' %}"></script>




{% endblock content %}

templates/website-details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{website.name}}
{% endblock title %}


{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/website-details.css' %}">
{% endblock stylesheets %}


{% block content %}
    <input type="hidden" name="website-id" value="{{website.id}}">
    <section class="website-pages">
        <div class="container">
            <div class="section__heading">
                <h1 class="section__heading__title">
                    {{website.name}}
                </h1>
                <p class="section__heading__text">
                    {{website.description}}
                </p>
            </div>
            
            <div class="section__content">
                <h4>إضافة صفحة جديدة</h4>
                <form class="add-page-form">
                    {% csrf_token %}
                    <div class="field">
                        <p>اسم الصفحة</p>
                        <input type="text" name="page-name-input" placeholder="اكتب اسم الصفحة" class="input text-input">
                    </div>
                    <a  class="btn btn-solid-dark btn-add-page">إنشاء صفحة</a>
                </form>
            </div>

            <br>

            <div class="section__content all-pages-grid">
                <div class="grid website-pages-grid">
                    {% if website.pages.all %}
                        {% for page in website.pages.all %}

                        <div class="col page">
                            <h3>{{page.name}}</h3>

                            <a href="{% url 'website:page-details' page.id %}" class="btn btn-outline btn-open-code">افتح الكود</a>
                        </div>

                        {% endfor %}
                    {% else %}
                        <center>
                            <h3>لا يوجد صفحات لعرضها</h3>
                        </center>
                    {% endif %}

                </div>
            </div>
        </div>
    </section>

    <br>

    <section>
        <div class="container">
            <div class="section__heading">
                <h1 class="section__heading__title">قواعد البيانات</h1>
                <p class="section__heading__text">كافة قواعد البيانات المربوطة بالمشروع</p>
                <div class="add-database-form">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field">
                            <p>اسم قاعدة البيانات</p>
                            <input type="text" class="text-input input" placeholder="اكتب اسم قاعدة البيانات" name="db-name-input">
                        </div>
                        <div class="field">
                            <p>نوع قاعدة البيانات</p>
                            <select name="db-type-input" id="db-type-input">

                                {% for type in db_types %}
                                    <option value="{{type.id}}">{{type.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </form>
                </div>
                <a class="btn btn-solid-dark btn-add-db">إضافة قاعدة بيانات جديدة</a>
            </div>

            <div class="section__content">
                <div class="grid website-databases">
                    {% for db in website.databases.all %}
                    <div class="col database">
                        <h3>
                            {{db.name}}
                        </h3>
                        <br>
                        <p>
                            عدد الجداول: 
                            <span>
                                {{db.tables.count}}
                            </span>
                        </p>
                        <a href="{% url 'website:db-details' db.id %}" class="btn btn-outline btn-open-code">التفاصيل</a>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <a href="{% url 'website:del-website' website.id %}" class="btn btn-solid-danger">حذف الموقع</a>
        </div>
    </section>


    <script src="{% static 'js/add-page.js' %}"></script>
    <script src="{% static 'js/add-database.js' %}"></script>

    {% endblock content %}